add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/justifier.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_data_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/chopper.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pool_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_data_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_register_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_register_write_interface.vhd
add_vhdl_file sources_1 WORK ../../../src/main/vhdl/dpram.vhd
add_vhdl_file sources_1 WORK ../../../src/main/vhdl/axi_dpram.vhd
add_vhdl_file sources_1 WORK ../../../src/main/vhdl/dpram_model_0.vhd
